codestates-seb/seb43_main_002

client/src/home/Board.js, client/src/home/Boards.js, client/src/home/Days.js, client/src/home/Footer.js, client/src/home/Header.js, client/src/home/HomeStyle.js, client/src/style/GlobalStyle.js
=> feat : Footer 기능 추가 / 게시글 작성은 미완료

client/src/App.js, client/src/map/Map.js, client/src/map/MapContent.js
feat : app.js에 map 링크 추가, map폴더 생성
=> feat : app.js에 map 링크 추가, map폴더 생성

client/package.json, client/src/App.js, client/src/axiosConfig.js, client/src/home/Header.js, client/src/setupProxy.js, client/src/store/boardSlice.js, client/src/style/GlobalStyle.js
=> Add SearchTerm_Not_Test_Yet

client/package-lock.json, client/package.json, client/src/store/boardSlice.js
=> NodeModules_Error_handled

client/src/style/GlobalStyle.js
=> max-height in globalwrap deleted

client/src/map/Map.js, client/src/map/MapStyle.js
feat - 지도 현재위치 버튼 수정, 목록 수정, 지도에서 마커를 클릭하면 나타나는 인포윈도우에 정보 추가
=> feat - 지도 현재위치 버튼 수정, 목록 수정, 지도에서 마커를 클릭하면 나타나는 인포윈도우에 정보 추가

Server/src/main/generated/com/branch/sikgu/board/mapper/BoardMapperImpl.java, Server/src/main/generated/com/branch/sikgu/comment/mapper/CommentMapperImpl.java, Server/src/main/java/com/branch/sikgu/meal/board/controller/BoardController.java, Server/src/main/java/com/branch/sikgu/meal/board/dto/BoardDto.java, Server/src/main/java/com/branch/sikgu/meal/board/entity/Board.java, Server/src/main/java/com/branch/sikgu/meal/board/mapper/BoardMapper.java, Server/src/main/java/com/branch/sikgu/meal/board/repository/BoardRepository.java, Server/src/main/java/com/branch/sikgu/meal/board/service/BoardService.java, Server/src/main/java/com/branch/sikgu/meal/comment/controller/CommentController.java, Server/src/main/java/com/branch/sikgu/meal/comment/dto/CommentDto.java, Server/src/main/java/com/branch/sikgu/meal/comment/entity/Comment.java, Server/src/main/java/com/branch/sikgu/meal/comment/mapper/CommentMapper.java, Server/src/main/java/com/branch/sikgu/meal/comment/repository/CommentRepository.java, Server/src/main/java/com/branch/sikgu/meal/comment/service/CommentService.java, Server/src/main/java/com/branch/sikgu/meal/history/dto/HistoryDto.java, Server/src/main/java/com/branch/sikgu/meal/history/entity/History.java, Server/src/main/java/com/branch/sikgu/meal/history/service/HistoryService.java, Server/src/main/java/com/branch/sikgu/member/entity/Member.java, Server/src/main/java/com/branch/sikgu/myPage/entity/MyPage.java, Server/src/main/java/com/branch/sikgu/myPage/service/MyPageService.java, Server/src/main/java/com/branch/sikgu/review/controller/ReviewController.java, Server/src/main/java/com/branch/sikgu/review/entity/Review.java, Server/src/main/java/com/branch/sikgu/review/service/ReviewService.java, Server/src/main/java/com/branch/sikgu/tag/entity/Tag.java, Server/src/test/java/com/branch/sikgu/board 2/BoardRestDocsTest.java, Server/src/test/java/com/branch/sikgu/comment/CommentRestDocsTest.java
Review 객체, 테이블 생성/Review, History 등 매핑
=> 1. Review 객체, 테이블 생성

.github/workflow/dev.yml
=> feat : yml 업로드

client/src/mypage/EditProfile.js, client/src/mypage/Footer.js, client/src/mypage/UserState.js, client/src/style/HomeStyle.js, client/src/style/ModalStyles.js, client/src/style/MypageStyle.js, client/src/style/NewHeaderFooterStyle.js, client/src/style/UserStateStyle.js
state/userpage/footer/header 병합
=> state/userpage/footer/header 병합

client/src/App.js, client/src/Signup/SignupForm.js, client/src/axiosConfig.js, client/src/login/NewLogin.js
=> set routes

client/src/axiosConfig.js, client/src/map/Map.js, client/src/mypage/EditProfile.js, client/src/mypage/MyPage.js, client/src/style/MapStyle.js, client/src/style/MypageStyle.js, client/src/style/NewHeaderFooterStyle.js, client/src/style/UserStateStyle.js
=> footer / header 통합 + CSS 수정

.github/workflows/gradleBE.yml
=> 죽음의 배포작업 v2

.github/workflows/gradleBE.yml, Server/build.gradle
=> 죽음의 배포작업 v3

Server/src/main/java/com/branch/sikgu/meal/board/repository/BoardRepository.java, Server/src/main/java/com/branch/sikgu/meal/board/service/BoardService.java, Server/src/main/java/com/branch/sikgu/member/controller/MemberController.java
getBoard() 빈배열 반환되는 문제 해결하고
mealTime 지나간건 반환안되게 수정했습니다.
=> BE - getBoard() 빈배열 반환되는 문제 해결

Server/src/main/generated/com/branch/sikgu/member/mapper/MemberMapperImpl.java, Server/src/main/java/com/branch/sikgu/auth/filter/JwtAuthenticationFilter.java, Server/src/main/java/com/branch/sikgu/auth/userdetails/MemberDetailsService.java, Server/src/main/java/com/branch/sikgu/meal/history/dto/HistoryDto.java, Server/src/main/java/com/branch/sikgu/meal/history/entity/History.java, Server/src/main/java/com/branch/sikgu/meal/history/service/HistoryService.java, Server/src/main/java/com/branch/sikgu/member/dto/MemberResponseDto.java, Server/src/main/java/com/branch/sikgu/member/entity/Member.java, Server/src/main/java/com/branch/sikgu/member/mapper/MemberMapper.java
=> HistoryDto 수정

Server/src/main/generated/com/branch/sikgu/member/mapper/MemberMapperImpl.java, Server/src/main/java/com/branch/sikgu/member/dto/MemberResponseDto.java, Server/src/main/java/com/branch/sikgu/member/mapper/MemberMapper.java
=> History dto 수정

client/src/map/Map.js
=> state / css 수정

Server/src/main/java/com/branch/sikgu/config/SecurityConfiguration.java, Server/src/main/java/com/branch/sikgu/config/WebConfig.java, Server/src/main/java/com/branch/sikgu/image/controller/FileUploadController.java, Server/src/main/java/com/branch/sikgu/meal/board/controller/BoardController.java, Server/src/main/java/com/branch/sikgu/meal/comment/controller/CommentController.java, Server/src/main/java/com/branch/sikgu/meal/history/controller/HistoryController.java, Server/src/main/java/com/branch/sikgu/meal/history/dto/HistoryDto.java, Server/src/main/java/com/branch/sikgu/member/controller/MemberController.java, Server/src/main/java/com/branch/sikgu/myPage/controller/MyPageController.java, Server/src/main/java/com/branch/sikgu/myPage/service/MyPageService.java, Server/src/main/java/com/branch/sikgu/review/controller/ReviewController.java
=> 사용 안하는 코드 제거

client/package-lock.json, client/package.json, client/src/home/Board.js, client/src/home/Comment.js, client/src/home/Days2.js, client/src/home/EditModal.js, client/src/home/PostModal.js, client/src/mypage/MyPage.js, client/src/mypage/UserPage.js, client/src/mypage/UserState.js, client/src/store/commentSlice.js, client/src/style/BoardStyle.js, client/src/style/GlobalStyle.js, client/src/style/HomeStyle.js
fix : 이미지 불러오기
fix : day 슬라이드
fix : userpage 이동
=> Fe feat/tag

Server/src/main/java/com/branch/sikgu/auth/filter/JwtAuthenticationFilter.java, Server/src/main/java/com/branch/sikgu/exception/ExceptionCode.java, Server/src/main/java/com/branch/sikgu/meal/board/controller/BoardController.java, Server/src/main/java/com/branch/sikgu/meal/board/service/BoardService.java
보드 참가 신청 거절 API 추가, 바디에 담아 보내던 토큰 삭제
=> BE - 보드 참가 신청 거절 API 추가, 바디에 담아 보내던 토큰 삭제

Server/src/main/java/com/branch/sikgu/review/entity/Review.java, Server/src/main/java/com/branch/sikgu/review/service/ReviewService.java
=> BE 테이블 명 오타 수정 + 리뷰 검증 로직 추가

.github/workflows/dev.yml
=>  the last commit to main project

Server/src/main/java/com/branch/sikgu/meal/board/service/BoardService.java
메인 화면 스케줄 2시간 전 스케줄부터 조회 가능하게 수정했습니다.
=> 메인 화면 스케줄 2시간 전 스케줄부터 조회 가능하게 수정
